# Copyright (c) 2013 ASMlover. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#  * Redistributions of source code must retain the above copyright
#    notice, this list ofconditions and the following disclaimer.
#
#    notice, this list of conditions and the following disclaimer in
#  * Redistributions in binary form must reproduce the above copyright
#    the documentation and/or other materialsprovided with the
#    distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

BIN_OUT	= libc-test.exe
BIN_DIR	= ..\bin
LIB_DIR	= ..\lib
CC	= cl -c -nologo 
LINK 	= link -nologo
MT 	= mt -nologo
CFLAGS 	= -O2 -W3 -MD -GS -Zi -Fd"vc.pdb" -DNDEBUG\
	-D_CRT_SECURE_NO_DEPRECATE -D_CRT_NONSTDC_NO_WARNINGS
LDFLAGS	= -DEBUG -PDB:$(BIN_OUT).pdb -manifest\
	-manifestfile:$(BIN_OUT).manifest -manifestuac:no\
	-LIBPATH:$(LIB_DIR) libc.lib
TEST_OBJS = main.obj\
	\
	test.obj test_arith.obj test_stack.obj test_atom.obj test_except.obj\
	test_memory.obj test_memcheck.obj test_arena.obj test_list.obj\
	test_slist.obj test_table.obj test_set.obj test_array.obj\
	test_sequence.obj test_ring.obj test_bit.obj test_format.obj\
	test_string.obj test_text.obj
RM	= del 
MD	= mkdir
RD	= rd /S /Q
CP 	= copy


all: bin

bin: $(BIN_OUT)

rebuild: clean all

install:
	if not exist $(BIN_DIR) $(MD) $(BIN_DIR)
	$(CP) $(BIN_OUT) $(BIN_DIR)

uninstall:
	if exist $(BIN_DIR) $(RD) $(BIN_DIR) 

clean:
	$(RM) $(TEST_OBJS) $(BIN_OUT) *.pdb *.manifest *.ilk




$(BIN_OUT): $(TEST_OBJS)
	$(LINK) -out:$(BIN_OUT) $(TEST_OBJS) $(LDFLAGS)
	$(MT) -manifest $(BIN_OUT).manifest -outputresource:$(BIN_OUT);1

{./}.c{./}.obj:
	$(CC) $(CFLAGS) $<
